"""criar tabelas estoque_saldos e estoque_movimentacoes

Revision ID: 16568d6a3cca
Revises: 510cf29436c0
Create Date: 2026-07-21 20:27:28.830927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16568d6a3cca'
down_revision: Union[str, Sequence[str], None] = '510cf29436c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_movimentacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loja_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_movimentacoes_tenant_id'), 'estoque_movimentacoes', ['tenant_id'], unique=False)
    op.create_table('estoque_saldos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loja_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'produto_id', 'tenant_id', name='uq_estoque_saldos_loja_produto_tenant')
    )
    op.create_index(op.f('ix_estoque_saldos_tenant_id'), 'estoque_saldos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_saldos_tenant_id'), table_name='estoque_saldos')
    op.drop_table('estoque_saldos')
    op.drop_index(op.f('ix_estoque_movimentacoes_tenant_id'), table_name='estoque_movimentacoes')
    op.drop_table('estoque_movimentacoes')
    # ### end Alembic commands ###
